name: Pipeline

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Test with VSTest
      run: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" /Framework:Frameworkuap10 test\bin\x86\Debug\Tests.build.appxrecipe'
      shell: cmd
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Display Environment Variables
      run: set
      shell: cmd
    
    - name: Build with MSBuild
      run: msbuild /restore /p:Platform=x86
      shell: cmd
      
    - name: Test with VSTest
      run: \"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe\" /Framework:Frameworkuap10 test\bin\x86\Debug\Tests.build.appxrecipe
      shell: cmd
